language: java
dist: xenial
sudo: false
jdk:
  - oraclejdk11
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

jobs:
  include:
    - jdk: oraclejdk8
      dist: trusty # oraclejdk8 install fails on Xenial
    - name: Reference Build
      jdk: openjdk8
      script:
        - ./gradlew check
        - ./gradlew jacocoTestReport
        - ./gradlew cleanJar
      after_success:
        - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew