dist: precise
language: java
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk8
    - openjdk7
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew cleanJar
after_success:
  - bash <(curl -s https://codecov.io/bash)
