language: java

matrix:
  include:
    - dist: trusty
      jdk: oraclejdk8
    - dist: precise
      sudo: false
      jdk:
        - oraclejdk7
        - openjdk7
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew cleanJar
after_success:
  - bash <(curl -s https://codecov.io/bash)
